using L4d2MatchmakingCore.Data;
using DotNet.Testcontainers.Builders;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Testcontainers.PostgreSql;

namespace L4d2MatchmakingCore.Tests;

[TestClass]
public sealed class PostgresPersistenceTests
{
    [TestMethod]
    public async Task AuditRowsReceiveDatabaseGeneratedIds()
    {
        PostgreSqlContainer container;

        try
        {
            container = new PostgreSqlBuilder("postgres:17")
                .WithDatabase("matchmaking")
                .WithUsername("matchmaking")
                .WithPassword("matchmaking-test-password")
                .Build();
            await container.StartAsync();
        }
        catch (DockerUnavailableException exception)
        {
            Assert.Inconclusive($"PostgreSQL container is unavailable: {exception.Message}");
            return;
        }

        await using (container)
        {
            var options = new DbContextOptionsBuilder<MatchmakingDbContext>()
                .UseNpgsql(container.GetConnectionString())
                .Options;
            await using var context = new MatchmakingDbContext(options);
            await context.Database.MigrateAsync();
            var audit = new LobbyOperationAudit
            {
                EventType = "test_audit",
                DetailsJson = "{}",
                ObservedAt = DateTimeOffset.UtcNow,
            };

            context.LobbyOperationAudits.Add(audit);
            await context.SaveChangesAsync();

            Assert.IsTrue(audit.Id > 0L);
        }
    }

    [TestMethod]
    public async Task AuditIdentityRepairMigrationAcceptsAnAlreadyRepairedDatabase()
    {
        PostgreSqlContainer container;

        try
        {
            container = new PostgreSqlBuilder("postgres:17")
                .WithDatabase("matchmaking")
                .WithUsername("matchmaking")
                .WithPassword("matchmaking-test-password")
                .Build();
            await container.StartAsync();
        }
        catch (DockerUnavailableException exception)
        {
            Assert.Inconclusive($"PostgreSQL container is unavailable: {exception.Message}");
            return;
        }

        await using (container)
        {
            var options = new DbContextOptionsBuilder<MatchmakingDbContext>()
                .UseNpgsql(container.GetConnectionString())
                .Options;
            await using var context = new MatchmakingDbContext(options);
            var migrator = context.Database.GetService<IMigrator>();
            await migrator.MigrateAsync("202608170004_TargetServerRotationCursor");
            await context.Database.ExecuteSqlRawAsync("""
                ALTER TABLE "LobbyOperationAudits"
                ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
                """);

            await migrator.MigrateAsync();
            context.LobbyOperationAudits.Add(new LobbyOperationAudit
            {
                EventType = "manual_identity_repair",
                DetailsJson = "{}",
                ObservedAt = DateTimeOffset.UtcNow,
            });
            await context.SaveChangesAsync();

            Assert.IsTrue(context.LobbyOperationAudits.Single().Id > 0L);
        }
    }

    [TestMethod]
    public async Task OneReservationLeaseExistsPerTarget()
    {
        PostgreSqlContainer container;

        try
        {
            container = new PostgreSqlBuilder("postgres:17")
                .WithDatabase("matchmaking")
                .WithUsername("matchmaking")
                .WithPassword("matchmaking-test-password")
                .Build();
            await container.StartAsync();
        }
        catch (DockerUnavailableException exception)
        {
            Assert.Inconclusive($"PostgreSQL container is unavailable: {exception.Message}");
            return;
        }

        await using (container)
        {
            var options = new DbContextOptionsBuilder<MatchmakingDbContext>()
                .UseNpgsql(container.GetConnectionString())
                .Options;
            await using var context = new MatchmakingDbContext(options);
            await context.Database.MigrateAsync();
            var targetServerId = Guid.NewGuid();

            context.ReservationLeases.Add(new ReservationLease
            {
                TargetServerId = targetServerId,
                OperationId = Guid.NewGuid(),
                ExpiresAt = DateTimeOffset.UtcNow.AddMinutes(1),
            });
            await context.SaveChangesAsync();
            context.ChangeTracker.Clear();
            context.ReservationLeases.Add(new ReservationLease
            {
                TargetServerId = targetServerId,
                OperationId = Guid.NewGuid(),
                ExpiresAt = DateTimeOffset.UtcNow.AddMinutes(2),
            });

            await Assert.ThrowsExceptionAsync<DbUpdateException>(() => context.SaveChangesAsync());
        }
    }
}
